---
apiVersion: v1
kind: Secret
metadata:
  name: quarkus-app-sample-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/apac-ce-janus-idp/janus-quarkus-app-sample-gitops